### ISSUE TITLE
Enhancement request: Option to write HDF5 format output

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/rawspec#19]
As of late, there is a lot of 2-phase spectra file creation:
1) Raw format --> Filterbank format (```rawspec```).
2) Filterbank format --> HDF5 format (```blimpy``` ```fil2h5``` or ```turbo_seti``` internally).

The Filterbank and HDF5 formats are logically consistent: same header fields (metadata) and spectra matrices.  So, in many cases, we are not gaining anything by keeping both forms around.  Note that if a Filterbank format was required, we can derive it from HDF5 using ```blimpy``` ```h52fil```.

I am proposing an option for ```rawspec``` to write output in HDF5 format directly, skipping the larger Filterbank file step.  This would save on data centre resources in the following general ways:
* Consumption of processing resources in conversion to HDF5.
* Disk storage.  If a Filterbank file occupies 7GB, its HDF5 equivalent occupies 4GB or less due to compression.  In this case, that would be a savings of ~63% by going directly to HDF5.

Another benefit would be that the ```rawspec``` utility could add useful fields from the raw file to the metadata of HDF5 such as NFPC (Number of Fine channels Per Coarse channel) and NANTS (Number of Antennas).  

For example, the NFPC value could beused by turbo_seti or hyperseti to compute precisely the number of coarse channels.  No need for user guessing or defaulting to some default value furnished by blimpy.  This is desirable for these reasons:
* The search bin is precisely the coarse channels specified in the raw file.
* The "Blank DC" (truncate the middle of bin spike) execution is accurate.

**Comment by wfarah** [comment]
That would be great! I would suggest for testing this mode:
- Either create a synthetic GUPPI raw file with turboSETI, or obtain data with a telescope (ATA, MeerKAT, GBT...)
- Run rawspec on GUPPI file, produce a filterbank output
- Run rawspec on GUPPI file again with the proposed added feature, produce HDF5 file
- Convert filterbank file to HDF5
- checksum the 2 HDF5 files

**Comment by texadactyl** [comment]
Almost forgot.  The NFPC value is used all over the search code employed by turbo_seti find_doppler.py.  There are 37 references to date.  So, having an accurate value is essential to search integrity.

**Comment by texadactyl** [comment]
@wfarah That is similar to how I have been testing even before integration:
```
rawspec --> .fil --> fil2h5 --> .h5 #1 --> turboSETI --> .dat --> convert to table 1
        ----------------------> .h5 #2 --> turboSETI --> .dat --> convert to table 2
```
Compare tables using numpy.isclose() for floating-point numbers.
```
.h5 #1 header --> convert to table 3
.h5 #2 header --> convert to table 4
Compare tables using numpy.isclose() for floating-point numbers.
```

**Comment by texadactyl** [comment]
v3.0.0
