### ISSUE TITLE
Add HDF5 output option

### ISSUE THREAD

**Issue by david-macmahon** [UCBerkeleySETI/rawspec#3]
Instead of just outputting to filterbank files, add ability to output to HDF5 files.  Ideally this would be selectable on a per output product basis.

**Comment by dmkunsman** [comment]
Is this still an open issue.  I was thinking about taking it up.

**Comment by david-macmahon** [comment]
Yes, it's still open.  It would be great to have this capability.  It would be even better if the HDF5 files were compatible with the "HDF5-ification" of Filterbank files that is performed by Breakthrough Listen's `fil2h5.py` script.  I'm trying to find a canonical reference for that process, but so far I haven't found anything other than the [`__write_to_hdf5_light`](https://github.com/UCBerkeleySETI/blimpy/blob/da0f0cea7ab66ae78fff3f069bff5d285f54b643/blimpy/io/hdf_writer.py#L146) function in [blimpy](https://github.com/UCBerkeleySETI/blimpy).  It looks like it basically attaches the filterbank headers as attributes of the `data` dataset.

**Comment by david-macmahon** [comment]
Please let me know if I can provide any more details for you.  Thanks!!!

**Comment by dmkunsman** [comment]
I have a more general question about raw spec.  Do you think this codebase would be a good springboard for start from if I wanted to try to implement a klt algorithm on guppi files?

**Comment by david-macmahon** [comment]
Rawspec makes heavy use of CuFFT, so if FFTs are good for KLT then rawspec could be a good springboard.  Other than that I guess rawspec would provide a nice C-based introduction to reading GUPPI RAW files in general.

**Comment by texadactyl** [comment]
Commandeered by issue #19
