### ISSUE TITLE
Issues with nants header field and options -S, -i, and -I

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/rawspec#34]
Using guppi_59229_47368_006379_40blocks.0000.raw from ATA (nants = 2), I generated the following scenarios:

[cases_nants_gt_1.pdf](https://github.com/UCBerkeleySETI/rawspec/files/7530635/cases_nants_gt_1.pdf)

My conclusions are that the following should be the only -I/--ICS and -S/--splitant option combinations when nants > 1:
* ```--ICS <weight>``` :: 1 ics .fil output and no other .fil files
* ```--splitant``` :: All of the antenna data are split into separate .fil files, 1 for each antenna.  No ics .fil is generated.
* Both ```--ICS <weight>``` and ```--splitant``` are specified :: All of the antenna data are split into separate .fil files, 1 for each antenna.  In addition, 1 ics .fil is generated.

Furthermore, the -i/--ics parameter should be removed.  Or, remove the -I/--ICS one.  But, just have one.

Error cases:
* If -I and -S are both missing when nants > 1, then that is an error.
* If nants = 1, then the presence of either -I or -S is an error.

**Comment by texadactyl** [comment]
@RocketRoss @wfarah @david-macmahon 

Please review.

**Comment by RocketRoss** [comment]
The concurrent ics (`-i`) was the original spec (#7), and I was just following orders. The ICS product comes at very little overhead after the FFT and so it was seen as a 'free' concurrent output...

To the point though, I think that the following is sooner preferable:

If nants > 1:
- default to split antenna (individual output filterbank files)... provide flag to not split (only a long version flag `--single/concatenated/amassed/messy-output`)
- keep concurrent and exclusive ICS flags (`-i` and `-I` stay as is)

If nants = 1:
- `-I` `-S` are each unreasonable, but ultimately harmless. If anything just ignore (doesn't the code already???). We have higher level pipelines that automatically call rawspec, but with somewhat static arguments, so making this an error would mean adding more brains to these super-pipelines... `pls..no...pls...`

**Comment by RocketRoss** [comment]
Oh and having had a look at your pdf, yeah `-I -S` should cancel to one or the other... but which one... maybe it's reasonable that both specified outputs were produced...
