### ISSUE TITLE
cuda API error returns should always be detected and processed correctly

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/rawspec#40]
Questions about error handling in rawspec_gpu.cu.

**Comment by texadactyl** [comment]
E.g. in rawspec_gpu.cu, line 1742:
```
  // For each output product
  for(i=0; i < ctx->No; i++) {
    // Clear power output buffer
    cuda_rc = cudaMemset(gpu_ctx->d_pwr_out[i], 0,
        abs(ctx->Npolout[i])*ctx->Nb*ctx->Ntpb*ctx->Nc*sizeof(float));
    if(cuda_rc != cudaSuccess) {
      PRINT_ERRMSG(cuda_rc);
      return 0;  <------------------------------------- should return 1 ?
    }
  }
```

**Comment by texadactyl** [comment]
In rawspec_gpu.cu, line 1760:
```
unsigned int rawspec_check_for_completion(rawspec_context * ctx)
{
  int complete = 0;
  cudaError_t rc;
  rawspec_gpu_context * gpu_ctx = (rawspec_gpu_context *)ctx->gpu_ctx;

  rc = cudaStreamQuery(gpu_ctx->compute_stream);
  if(rc == cudaSuccess) {
    complete++;
  } <--------------------------------------- What is rc != cudaSuccess ?

  return complete;
}
```

**Comment by texadactyl** [comment]
Not all of the rc != cudaSuccess processing call ```rawspec_cleanup(ctx)``` when they detect an error.
Should cleanup always be invoked when a cuda error is detected?

**Comment by david-macmahon** [comment]
> In rawspec_gpu.cu, line 1760:
> 
> ```
> unsigned int rawspec_check_for_completion(rawspec_context * ctx)
> {
>   int complete = 0;
>   cudaError_t rc;
>   rawspec_gpu_context * gpu_ctx = (rawspec_gpu_context *)ctx->gpu_ctx;
> 
>   rc = cudaStreamQuery(gpu_ctx->compute_stream);
>   if(rc == cudaSuccess) {
>     complete++;
>   } <--------------------------------------- What is rc != cudaSuccess ?
> 
>   return complete;
> }
> ```

A `cudaSuccess` return value from `cudaStreamQuery` means the stream has completed.  Any other value means the stream has not completed.  This function translates a `cudaSuccess` return value into a C "true" value (i.e. non-zero) and any non-`cudaSuccess` return value into a C "false" value (i.e. zero).  Maybe NVIDIA could have invented yet another constant such as `cudaStreamComplete` to indicate that the stream has completed, but they opted not to.

**Comment by david-macmahon** [comment]
The check around line 1742 could be made better for sure.  I think the enclosing function, `rawspec_reset_integration` should return the number of output buffers that were not successfully reset/cleared.  So if they all are reset OK, `rawspec_reset_integration` will return 0 for success.  If the clearing of one buffer fails, the return value should be incremented, but the remaining output buffers should still be (attempted to be) cleared.  Any non-zero return from `rawspec_reset_integration` would indicate problems and the larger the value, the more buffers had problems being cleared.

**Comment by texadactyl** [comment]
Thanks for the line 1760 explanation.

Line 1742: In rawspec.c, the only place that ```rawspec_reset_integration``` is called is in this context: "Same as previous stem, just reset for new integration".  Note that the return code is ignored.  Shouldn't rawspec exit with an error status if there is any sort of GPU failure?  FWIW, that is a very long if-then-else starting at line 555 - very hard to read.
