### ISSUE TITLE
individual filterbank output

### ISSUE THREAD

**Issue by siemion** [UCBerkeleySETI/rawspec#6]
Add the ability to output individual filterbank files from multi-antenna input rather than quasi-compliant "multi-antenna filterbank"

**Comment by jack-h** [comment]
As a first approach, we're going to implement a flag to select a single antenna from a raw file to generate the output .fil . Can easily parallelize over antennas to get all the files

**Comment by david-macmahon** [comment]
rawspec already supports a user-specified subset of coarse channels that can be used to process only channels from a single antenna.  No need to add anything special for that.  The only drawback is reading the RAW file multiple times.

**Comment by jack-h** [comment]
but not a sub-coarse channel selection, right?

**Comment by david-macmahon** [comment]
You can't read a sub-coarse channel on input.  On the write side it currently writes out all fine channels for the coarse channels you select.  If you want the ability to output a subset of the generated fine channels, it's probably better as a separate issue/feature request since it's orthogonal to selecting a single antenna from a RAW file.

**Comment by jack-h** [comment]
Ha -- I'm responding to this in email. I totally thought this was the other
issue.

**Comment by RocketRoss** [comment]
> already supports a user-specified subset of coarse channels

So all that would be needed is an interface ontop of the coarse channel selection that works off of antenna selection. I can see it

I don't see why the file would have to be read any more times for antenna selection.

**Comment by jack-h** [comment]
You would have to run raw_spec N times with different flags to generate N
antennas -- rather than reading it once and writing all the files. It's not
obvious [to me] what the speed penalty for doing that is, you're still
reading ~the same number of bytes total, just not in one contiguous block.

**Comment by dmkunsman** [comment]
This still open.  Anyway I could help with this?

**Comment by RocketRoss** [comment]
@dmkunsman I have implemented it in 2 ways:
#9 provides `-a ANT` which enables selective processing of a single antenna's channels. There exists an understanding that there may be a way to bash script parallel rawspec calls to process each antenna within the RAW data. The PR has received a first round of review from @david-macmahon. 

#11 provides `-s` which instructs rawspec to split the output by antenna, and write to individual files. 

I tested the selective antenna processing by generating a RAW file where only one antenna's values were non-zero (populated with random bytes). I tested the split-output by matching the filterbank files against those generated by selective antenna processing.

I believe both are in working order, but perhaps you'd be willing to further verify. Other than that, I think #9 and #11 are just awaiting review->refine->merge.

**Comment by RocketRoss** [comment]
I have a local branch that has merged #9, #11 and #12, and it is currently in use at SETI-ATA. So these are compatible PRs.

**Comment by RocketRoss** [comment]
[This](https://drive.google.com/file/d/1rosmrLY_2vV_5IVqY8pnXtcwjI0QGcmu/view?usp=sharing) is the RAW GUPPI file I used...

**Comment by RocketRoss** [comment]
6fab77160b87cc56a642f66f50529bed9ffa45a6 closes this too.
