### ISSUE TITLE
incoherent sum mode

### ISSUE THREAD

**Issue by siemion** [UCBerkeleySETI/rawspec#7]
For multi-antenna input, add the ability to optionally and concurrently output an incoherently summed data product with an optional set of per-antenna weights.

**Comment by RocketRoss** [comment]
@texadactyl This could be closed now: 6fab77160b87cc56a642f66f50529bed9ffa45a6 🎉

**Comment by texadactyl** [comment]
@RocketRoss 
I'll take it that you or someone else in ATA has fully tested this request.
True?  If so, then this issue can be closed.
Pity you are not on Seti slack!

cc: @wfarah

**Comment by texadactyl** [comment]
Okay, "@radonnachie" found me on seti slack.
